"""empty message

Revision ID: 83348fcb34e8
Revises: d0da5ff04fb2
Create Date: 2025-06-28 14:46:11.792558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83348fcb34e8'
down_revision = 'd0da5ff04fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('drive',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('drive',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
